In [1]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import brown
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import wordnet
from collections import  Counter
import spacy
from spacy import displacy
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [2]:
df=pd.read_csv('DATA_After_Cleaning.csv')

In [3]:
count_vec = CountVectorizer(stop_words='english',ngram_range=(1, 2), max_features= 7)
count_vec.fit(df['Updated_Review'])
text_vectorized = pd.DataFrame(count_vec.transform(df['Updated_Review']).toarray(),
                               columns=count_vec.get_feature_names())
text_vectorized

       book  like  love  make  read  story  time
0         2     0     1     1     1      0     0
1         0     0     0     0     0      0     0
2         2     0     1     0     1      0     0
3         4     1     1     0     3      1     0
4         7     2     0     1     0      0     1
...     ...   ...   ...   ...   ...    ...   ...
63885     2     0     0     2     2      0     0
63886     1     0     0     1     1      1     4
63887     5     2     0     0     4      1    12
63888     1     1     0     0     1      0     0
63889     0     0     0     1     0      0     0

[63890 rows x 7 columns]

In [4]:
final_df = df.merge(text_vectorized,left_index=True, right_index=True)

In [5]:
final_df.to_csv('After_cleaning.csv',index=False)